web:
  build: ./
  volumes:
    - "~/starhackit/server:/app_source"
  ports:
    - "9000:9000"
  links:
    - "rabbitmq"
    - "postgres"
    - "redis"
  command: bash -c "cp -r /app_source /app && npm start"

postgres:
  image: postgres
  expose:
    - "5432"
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
redis:
  image: redis
